# Generated by Django 3.0.7 on 2020-07-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='resume_name',
            field=models.CharField(default='resume', max_length=100),
        ),
        migrations.AddField(
            model_name='educ',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educ',
            name='resume_name',
            field=models.CharField(default='resume', max_length=100),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='resume_name',
            field=models.CharField(default='resume', max_length=100),
        ),
        migrations.AddField(
            model_name='skills',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skills',
            name='resume_name',
            field=models.CharField(default='resume', max_length=100),
        ),
        migrations.AddField(
            model_name='workexp',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexp',
            name='resume_name',
            field=models.CharField(default='resume', max_length=100),
        ),
    ]
